modLoader = "javafml"
loaderVersion = "[41,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "compost"
version = "${version}"
displayName = "Compost"
displayTest = "IGNORE_SERVER_VERSION"
displayURL = "https://github.com/yurisuika/Compost"
issueTrackerURL = "https://github.com/yurisuika/Compost/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Make composters turn your food waste into whatever you want!
'''

[[dependencies.compost]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "SERVER"

[[dependencies.compost]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.compost]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[9,)"
ordering = "NONE"
side = "CLIENT"